### ISSUE TITLE
No "Add all the subnets related to this VPC" option exists

### ISSUE THREAD

**Issue by Melvillian** [awsdocs/amazon-rds-user-guide#101]
Short: 
I expect to see the "Add all the subnets related to this VPC" option when making an DB Subnet, but instead all I see is a dropdown of all of my subnets which I must individually select.

Longer:
In the "Create a DB Subnet Group" guide's Step 5 it says:

In the Add subnets section, choose **Add all the subnets related to this VPC**. 

Yet I did not see this option in the dropdown. 

See the photo below where my 3 subnet IDs have been anonymized.

![blur-photo com_1588775976](https://user-images.githubusercontent.com/1884338/81190551-f8741180-8f85-11ea-9561-068b362d9383.jpg)

**Comment by randyurbano** [comment]
Thanks for your feedback. I confirmed that the documentation should be updated for the change in the screen, and I will update it

**Comment by randyurbano** [comment]
I published the documentation updates. For example:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_VPC.WorkingWithRDSInstanceinaVPC.html#USER_VPC.CreateDBSubnetGroup

Thanks again for your feedback. Let me know if you have more comments or questions.
