### ISSUE TITLE
Is "Inconsistent InnoDB Buffer Pool Size" still an issue?

### ISSUE THREAD

**Issue by stefanwork** [awsdocs/amazon-rds-user-guide#11]
Hi there,

I am wondering if this issue is still present in MySQL 5.7.21?

https://github.com/awsdocs/amazon-rds-user-guide/blob/bf9f9f4fd56500a7b1ec7987b5e1a67f0818be00/doc_source/MySQL.KnownIssuesAndLimitations.md#inconsistent-innodb-buffer-pool-size

The bug that is referenced (https://bugs.mysql.com/bug.php?id=79379) says "Version: 5.7.9". But I am not able to find the bug referenced in any 5.7 changelog items.

Thanks!

**Comment by randyurbano** [comment]
Thanks for the question. I confirmed with development that the issue still applies to MySQL 5.7.21.
