### ISSUE TITLE
Missing Data API Limit

### ISSUE THREAD

**Issue by jaeyeonling** [awsdocs/amazon-rds-user-guide#110]
```java
com.amazonaws.services.rdsdata.model.AWSRDSDataException: Rate exceeded (Service: AWSRDSData; Status Code: 400; Error Code: ThrottlingException;
```

I can't find the above error content for API Limit in the document.

**Comment by randyurbano** [comment]
Thanks for your feedback. I'm asking the service team about this error.

**Comment by randyurbano** [comment]
I updated the documentation to add the Data API quotas that were missing:

Quotas in Amazon Aurora
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/CHAP_Limits.html#RDS_Limits.Limits

I also added the following note to the Data API topic:

"The maximum number of requests per second is 1,000."

Running a SQL Statement
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html#data-api.calling.cli.execute-statment

Running a Batch SQL Statement Over an Array of Data
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html#data-api.calling.cli.batch-execute-statement
