### ISSUE TITLE
I can't find a comprehensive list of all generic and MS SQL Server Specific RDS functionalities, i.e rdsadmin and msdb.dbo.rds_ objects.

### ISSUE THREAD

**Issue by Prof-hu** [awsdocs/amazon-rds-user-guide#118]
https://github.com/awsdocs/amazon-rds-user-guide/blob/master/doc_source/Appendix.SQLServer.CommonDBATasks.md
This is all I could find.
I was looking for a way to query a very basic RDS Instance property, its instance name, and couldn't even find a way to do that after 2 days of googling.

**Comment by WooSung-Jung** [comment]
What your database product?

**Comment by Prof-hu** [comment]
@WooSung-Jung 
> What your database product?
I updated the title (it was not specific enough, indeed), though I mentioned msdb and referenced the SQL Server docs, so it was kind of there anyways...

**Comment by Prof-hu** [comment]
Also I got a feedback reply on other channels, that at least the MS SQL SPs are listed on the bottom of this page, which I was not able to find, it is kind of hidden in a loooong article, and even google couldn't find an show to me. Anyways, a way to query the RDS DB Instance Identifier and a list of other rdsadmin objects available is still something I'm looking for.

**Comment by claytran** [comment]
Here are a few queries. I’m still working on finding the DB instance identifier.

To find the databases:
SELECT * FROM sysservers
SELECT @@servername AS [ServerName]
SELECT DB_NAME() AS [Current Database]
SELECT * FROM sysdatabases;

To find the stored procedures in msdb:
SELECT *
FROM [msdb].INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_TYPE = 'PROCEDURE'
AND LEFT(ROUTINE_NAME, 3) IN ('rds');

In rdsadmin:
SELECT *
FROM [rdsadmin].INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_TYPE = 'PROCEDURE';

To find all the objects in msdb:
use msdb
select * from sys.all_objects;

All the views in msdb:
use msdb
select * from sys.views;

**Comment by claytran** [comment]
From one of the SQL Server engineers:

A DB instance identifier can't be retrieved via a SQL query. What a customer can do is put the DB instance identifier into some table once a RDS instance is created.
