### ISSUE TITLE
Offer alternatives/workarounds to removing encryption from an RDS database

### ISSUE THREAD

**Issue by matthewcummings** [awsdocs/amazon-rds-user-guide#125]
This page states that you cannot remove encryption from an RDS instance: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html#Overview.Encryption.Limitations

That's fine but you could also mention workarounds for this. I believe that you can accomplish this by using a tool like DMS, a home grown script or a connector from a third party vendor.
While generally, you wouldn't want to remove encryption, it's the kind of thing you might need to do in an emergency.

It's frustrating when the AWS doc leads to dead ends like this with a "Oh well, you're screwed if you're stuck in this situation".

**Comment by matthewcummings** [comment]
To be clear, this _should be_ obvious to most people who get into this situation but just adding a note explaining what to do next would be helpful.

**Comment by randyurbano** [comment]
Thanks for your feedback. I discussed this issue with the service team, and we decided to add the following bullet to the section:

- You can't unencrypt an encrypted DB instance. However, you can export data from an encrypted DB instance and import the data into an unencrypted DB instance. 

There are other workarounds, but the consensus was that unencrypting a DB instance isn't a common scenario and that export/import would be the easiest method for doing it. 

Let me know if you have other comments or questions.

**Comment by matthewcummings** [comment]
Great, I know it's minor but that should allay the initial "holy crap I'm screwed" feeling you get if you end up in this scenario.
