### ISSUE TITLE
In https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Tutorials.WebServerDB.CreateWebServer.html, 9th step failing with Gateway error 

### ISSUE THREAD

**Issue by Anulanasha** [awsdocs/amazon-rds-user-guide#128]
Gateway Timeout
The gateway did not receive a timely response from the upstream server or application

**Comment by randyurbano** [comment]
Thanks for your feedback. Can you provide more information about the problem you are having? Is this the step that is failing?

9. Verify that your web server successfully connects to your DB instance by opening a web browser and browsing to http://EC2 instance endpoint/SamplePage.php, for example: http://ec2-55-122-41-31.us-west-2.compute.amazonaws.com/SamplePage.php. 

If so, did all of the other steps in the tutorial succeed?

**Comment by Anulanasha** [comment]
Yes this is the step where it failed. All other steps in the tutorial succeeded.

**Comment by randyurbano** [comment]
Did you complete all of the steps here to create your VPC?

Tutorial: Create an Amazon VPC for use with a DB instance 
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Tutorials.WebServerDB.CreateVPC.html

Make sure the steps in this section completed successfully:
Create a VPC security group for a public web server
