### ISSUE TITLE
RDS aurora DB-instance creation problem

### ISSUE THREAD

**Issue by palakbadgujar** [awsdocs/amazon-rds-user-guide#13]
aws rds create-db-cluster --db-cluster-identifier sample-cluster --engine aurora-mysql \
     --engine-version 5.7.12 --master-username user-name --master-user-password password \
     --db-subnet-group-name mysubnetgroup --vpc-security-group-ids sg-c7e5b0d2

when we entered above code this cluster module is not available  and if we entered aws rds help so in that to this create-db-cluster module is not available thn why they why it is available  in aws official documentation.

**Comment by randyurbano** [comment]
Thanks for the feedback. Could you copy and paste the error message in a comment here? The problem might be that you need to specify valid values for the subnet group name and security group ID. The specified subnet group and security group must exist in your environment.

**Comment by palakbadgujar** [comment]
yes you were write previously it was not even supporting the create-db-cluster but when i upgrade the awscli by using :- 
command:- pip install –upgrade awscli with the awscli version 1.15 it is supporting cluster creation module.
 and i tried with the following command:-
aws rds create-db-cluster --db-cluster-identifier palak-cluster --engine aurora-mysql \
     --engine-version 5.7.12 --master-username palak --master-user-password db123456 \
     --db-subnet-group-name default --vpc-security-group-ids subnet-b97883c0
the same error as you depict previously came  but by using the the guide line of you's now it is working thankyou so much randy.
