### ISSUE TITLE
Consolidating Postgres RDS databases into fewer  Postgres RDS database instances

### ISSUE THREAD

**Issue by jeergall** [awsdocs/amazon-rds-user-guide#138]
I am working on consolidation of AWS RDS postgres db instances. There are around 40 individual postgres RDS db instances. These 40 instances are not utilized fully. CPU Utilization is below 5% for all. So planning to migrate / consolidate these 40 instances into few instances like around 4. I am  thinking  of two options. 1. Use pg_dump and 2. Use pg_transport. I would like  to know what is the best option for this. I haven't used pg_transport. Any suggestions highly appreciated. I am little new to AWS RDS postgres db instances.

**Comment by buenks** [comment]
Hi there.

Thanks very much for taking the time to submit feedback on our documentation. It sounds like you actually have a technical support question. I suggest that you post it on the Amazon SSS forum, which is a good resource: https://forums.aws.amazon.com/forum.jspa?forumID=XYZ

 You might also consider signing up for AWS technical support: https://aws.amazon.com/premiumsupport/

Regards,
Terence
