### ISSUE TITLE
Delete default.aurora-mysql5.7 parameter group

### ISSUE THREAD

**Issue by palakbadgujar** [awsdocs/amazon-rds-user-guide#14]
At the time of deleting the parameter group from aws console of rds i am facing following problem:-

error:- Failed to delete default.aurora-mysql5.7: Default DBParameterGroup cannot be deleted: default.aurora-mysql5.7 (Service: AmazonRDS; Status Code: 400; Error Code: InvalidDBParameterGroupState; Request ID: 5e839386-71ef-45ef-baaf-a136a880f49f)

the same thing i tried with awscli following error is coming:-
command:-  aws rds delete-db-parameter-group --db-parameter-group-name default.aurora-mysql5.7
error:- An error occurred (InvalidDBParameterGroupState) when calling the DeleteDBParameterGroup operation: Default DBParameterGroup cannot be deleted: default.aurora-mysql5.7

**Comment by randyurbano** [comment]
Thanks for the feedback. You can't delete a default parameter group. See the constraints in the documentation here:

https://docs.aws.amazon.com/cli/latest/reference/rds/delete-db-parameter-group.html

You can create a new parameter group and modify your DB instance or DB cluster to use the new parameter group. See the documentation here:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithParamGroups.html#USER_WorkingWithParamGroups.Creating
