### ISSUE TITLE
Average active executions table

### ISSUE THREAD

**Issue by pdurbin** [awsdocs/amazon-rds-user-guide#151]
From https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.Overview.ActiveSessions.html

I believe that both cells highlighted in blue below should be 380 instead of 360.

![Screen Shot 2021-10-20 at 3 22 42 PM](https://user-images.githubusercontent.com/21006/138158500-c4d41bac-8e36-4e53-86b5-d32155d84462.png)

I would have made a pull request instead of opening an issue but I don't think this table is in the source. Good idea to put the docs on GitHub. Thanks.

```
>>> 360/180
2.0
>>> 360/240
1.5
>>> 
>>> 380/180
2.111111111111111
>>> 380/240
1.5833333333333333
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
