### ISSUE TITLE
Explanation for SQL_MODE default

### ISSUE THREAD

**Issue by edhgoose** [awsdocs/amazon-rds-user-guide#160]
Hello, I noticed that the default for RDS mysql 5.7 and 8 parameter groups `SQL_MODE` option is different from the MySql default.

The default on MySql 5.7 is specified here: https://dev.mysql.com/doc/refman/5.7/en/faqs-sql-modes.html#faq-mysql-what-default-mode 

The default for mysql 8 is specified here: https://dev.mysql.com/doc/refman/8.0/en/faqs-sql-modes.html#:~:text=The%20default%20SQL%20mode%20in,%2C%20%E2%80%9CServer%20SQL%20Modes%E2%80%9D.

Whereas the RDS default seems to be  `NO_ENGINE_SUBSTITUTION` for both versions. 

I understand how to change it, but I wondered if it was possible to document why the default is different, whether there are any benefits to the different default and why AWS recommends this default?

The reason for asking is that we noticed a difference between our local environments and AWS RDS and we're unsure on whether we should deliberately override the AWS recommendation. All the documentation I can find is about changing it, not why it's set like this.

**Comment by nnat425** [comment]
Bump. We're seeing something similar in our system.

**Comment by amylmill** [comment]
Thanks for reaching out about this.

RDS might change the default values for some parameters. If you require different values, you can modify them in the database parameter group.

**Comment by edhgoose** [comment]
@amylmill we're asking for documentation of why the default is different and what the pros/cons/implications of it are.

We know we can change it.

Could we reopen this and have that documented please?

**Comment by amylmill** [comment]
@edhgoose Unfortunately, we do not publish the reasons for parameter differences.
