### ISSUE TITLE
RDS En Dash instead of Hyphen-Minus in code blocks on 

### ISSUE THREAD

**Issue by packplusplus** [awsdocs/amazon-rds-user-guide#169]
On [CHAP_PostgreSQL.md](https://github.com/awsdocs/amazon-rds-user-guide/blob/main/doc_source/CHAP_PostgreSQL.md) there is a code block with En Dash instead of Hyphen-Minus https://github.com/awsdocs/amazon-rds-user-guide/blob/e2196fb92fb0e52fdfe5fe57327edcd73f32c607/doc_source/CHAP_PostgreSQL.md?plain=1#L128

* https://unicode-table.com/en/2013/
* https://unicode-table.com/en/002D/

A minor PR would be easy to create, but I'm wondering if a more thorough audit would be needed before I try to create such a minor thing.

**Comment by dbagansk** [comment]
Hi,  Thank you very much for this correction.  I will check for additional occurrences.

**Comment by dbagansk** [comment]
This issue is fixed in the documentation.
Thank you for your feedback.
