### ISSUE TITLE
Broken link on `Working with read replicas for Amazon RDS for PostgreSQL`

### ISSUE THREAD

**Issue by ermiyaeskandary** [awsdocs/amazon-rds-user-guide#171]
Hello,

There seems to be a broken link [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PostgreSQL.Replication.ReadReplicas.html#USER_PostgreSQL.Replication.ReadReplicas.Configuration) for 'Streaming Replication':

> RDS for PostgreSQL uses PostgreSQL native streaming replication to create a read-only copy of a source DB instance. This read replica DB instance is an asynchronously created physical replica of the source DB instance. It's created by a special connection that transmits write ahead log (WAL) data from the source DB instance to the read replica. For more information, see [Streaming Replication](https://https//www.postgresql.org/docs/14/warm-standby.html#STREAMING-REPLICATION) in the PostgreSQL documentation.

[https//www.postgresql.org/docs/14/warm-standby.html#STREAMING-REPLICATION](https//www.postgresql.org/docs/14/warm-standby.html#STREAMING-REPLICATION)  returns 'This site can’t be reached' for me.

**Comment by dbagansk** [comment]
Thank you for this correction.  The document will be updated.
