### ISSUE TITLE
Description of administrative accounts of AWS RDS

### ISSUE THREAD

**Issue by ad-m-ss** [awsdocs/amazon-rds-user-guide#172]
Could you provide documentation for all users added to AWS RDS for PostgrSQL to provide management? Some of them are documented ( https://github.com/awsdocs/amazon-rds-user-guide/blob/88ba46fb979ada9f0f8303ca249408df56adfc44/doc_source/Appendix.PostgreSQL.CommonDBATasks.md#understanding-the-rds_superuser-role ), but in my instance `rdsrepladmin` which does not have description in documentation at all.

It is essential for the audit to prove that all existing user accounts are necessary as well as to prove that the indicated accounts are managed by AWS and that AWS keeps them safe under shared responsibility.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
