### ISSUE TITLE
Converting from rds on-demand to rds reserved instance

### ISSUE THREAD

**Issue by yasinkayade** [awsdocs/amazon-rds-user-guide#174]
Hi,

I use aws rds postgresql to store data (rds on demand instance type). Is it possible to convert it to a reserved instance without creating a new instance via CLI or console? On the internet there is pretty much info about ec2, but cannot see about rds.

**Comment by kwiseth-AWS** [comment]
Hello, have you looked at the information in this section:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_OnDemandDBInstances.htm

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
