### ISSUE TITLE
Need to update PostgreSQL upgrade version table for 14.4

### ISSUE THREAD

**Issue by alexhollis** [awsdocs/amazon-rds-user-guide#177]
Currently, the Postgres upgrade table stops at **14.3**, this should be updated to reflect the latest version now being **14.4**: 
https://github.com/awsdocs/amazon-rds-user-guide/blob/main/doc_source/USER_UpgradeDBInstance.PostgreSQL.md#USER_UpgradeDBInstance.PostgreSQL.MajorVersion

**Comment by dbagansk** [comment]
Thank you for your feedback.  We will update the documentation.

**Comment by dbagansk** [comment]
I apologize for the delay.  The information needs to be verified before updating the documentation.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
