### ISSUE TITLE
perf insights supported engines changed?

### ISSUE THREAD

**Issue by maaarghk** [awsdocs/amazon-rds-user-guide#188]
https://github.com/awsdocs/amazon-rds-user-guide/blob/4ea9161be71392e8b3f596c19b3f8dcdd892b849/doc_source/USER_PerfInsights.Overview.Engines.md?plain=1#L11

seems this was changed as on t4g / 10.6 i can no longer enable perf insights (Was possible a few weeks ago) - not sure if a docs update or just a bug with RDS but maybe you can find out

**Comment by bharthis** [comment]
Thank you for the feedback, @maaarghk. I've confirmed with the engineer and will publish the updates in document in a couple of days.

**Comment by bharthis** [comment]
Hi @maaarghk, The update is published and available on this page: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.Overview.Engines.html

**Comment by maaarghk** [comment]
@bharthis This removes mention of t4g but it seems like performance insights is also not supported on t4g.micro or t4g.small for Mariadb 10.6. I suggest checking again the exhaustive list of requirements with the engineers and leaving the issue open until confirmed
