### ISSUE TITLE
Online documentation regarding Performance Insights not in sync with GitHub?

### ISSUE THREAD

**Issue by holtkamp** [awsdocs/amazon-rds-user-guide#189]
The URL https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.Overview.Engines.html currrently displays: 

![Screenshot 2023-01-19 at 13 20 01](https://user-images.githubusercontent.com/776405/213441799-3f3049dd-eceb-4626-a5cb-972fc33e54a9.png)

Note the third column. 

When trying to enable Performance Insights for MySQL on `db.t4g.micro` and `db.t4g.small` instances, this seems not possible, so I wanted to _add_ this limitation by editting the page using the link mentioned on the page, which leads me to https://github.com/awsdocs/amazon-rds-user-guide/tree/main/doc_source/USER_PerfInsights.Overview.Engines.md which displays: 

![Screenshot 2023-01-19 at 13 23 41](https://user-images.githubusercontent.com/776405/213442261-0ea51be1-db20-4972-8e26-a07f2eecc372.png)

This content is different from the published page?

https://github.com/awsdocs/amazon-rds-user-guide/blob/4ea9161be71392e8b3f596c19b3f8dcdd892b849/doc_source/USER_PerfInsights.Overview.Engines.md also suggests that Performance Insights for MySQL **is** supported for all `db.t4g` instances (including `db.t4g.micro` and `db.t4g.small`). But this seems not the case when trying to enable it in AWS RDS?

So now I am confused 😉 , what is the proper documentation? What is the support for Performance Insights on MySQL on `db.t4g` instances? This information would be useful when trying to determine whether to upgrade from `db.t3` to `db.t4g`.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
