### ISSUE TITLE
Wrong parameter default in documentation

### ISSUE THREAD

**Issue by meyerovb** [awsdocs/amazon-rds-user-guide#191]
[This doc](https://github.com/awsdocs/amazon-rds-user-guide/blob/main/doc_source/PostgreSQL.Concepts.General.SSL.md) says default value for forcessl is 0 but for postgres 15 default param group it’s 1

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
