### ISSUE TITLE
Encrypting an unencrypted Aurora Postgres or Aurara Mysql instance

### ISSUE THREAD

**Issue by wilchoon** [awsdocs/amazon-rds-user-guide#25]
This statement from the Doc, seems to be misleading

"You can create an encrypted Read Replica of an unencrypted DB instance, and you can create an unencrypted Read Replica of an encrypted DB instance. "

Tried to reproduce this with Aurora, the encryption option is available and when you select it, it ends up not creating an encrypted instance from the unencrypted aurora instance. 

This is made clear here --> https://aws.amazon.com/rds/aurora/faqs/

Q: Can I encrypt an existing unencrypted database?

Currently, encrypting an existing unencrypted Aurora instance is not supported. To use Amazon Aurora encryption for an existing unencrypted database, create a new DB Instance with encryption enabled and migrate your data into it.

**Comment by randyurbano** [comment]
Thanks for your feedback. Please see this section:

Limitations of Amazon RDS Encrypted Instances
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html#Overview.Encryption.Limitations

Let me know if you think it documents the restriction.

**Comment by jong82** [comment]
I ran into the same issue with postgresql aurora specifically.  While it is documented that this option is not possible, it should not be available in the aws console which is the misleading part.  I ended up cutting over to an entirely new encrypted cluster using pg_dump.  DMS is not a possibility for a cutover since pg aurora is not a supported source.  Its not the easiest solution but the only one that I could get to work.

**Comment by aolley** [comment]
That limitation, as written, implies its not possible to have an encrypted read replica of a unencrypted source **at all**.

When in fact it appears to be possible for some engines - from RDS console recommendations: "The MySQL, MariaDB, and PostgreSQL engines also support creating an encrypted Read Replica from a source that isn't encrypted.".

**Comment by randyurbano** [comment]
This limitation in the documentation is correct as far as I know:

"You can't have an encrypted Read Replica of an unencrypted DB instance or an unencrypted Read Replica of an encrypted DB instance."

Limitations of Amazon RDS Encrypted DB Instance
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html#Overview.Encryption.Limitations

Can you provide more information about where you saw the statement that it is supported? Thanks.

**Comment by aolley** [comment]
In the RDS console, when viewing an unencrypted PostgreSQL DB, on the "recommendations" section when viewing the configuration pane, I [see this](https://imgur.com/VfLoNjD).

Text from the screenshot:

Recommendation type | Recommendation
-- | --
Encryption disabled | Your DB instance is not enabled for encryption of data at rest. You can encrypt your existing Amazon RDS DB instances by restoring from an encrypted snapshot. The MySQL, MariaDB, and PostgreSQL engines also support creating an encrypted Read Replica from a source that isn't encrypted.

**Comment by randyurbano** [comment]
Thanks. I will investigate this inconsistency.

**Comment by randyurbano** [comment]
The Amazon RDS service team confirmed that the documentation is correct. The Recommendations page is not correct. We will update the Recommendations page as soon as possible. Thanks again for your feedback. Let me know if you have more questions or comments.

**Comment by shaikidris** [comment]
> The Amazon RDS service team confirmed that the documentation is correct. The Recommendations page is not correct. We will update the Recommendations page as soon as possible. Thanks again for your feedback. Let me know if you have more questions or comments.

Still it is not updated and misleading DBA and impacting the plans.

**Comment by yacinelazaar** [comment]
Well, Im planning to pass a certification soon so which one is it. This is really confusing. I ultimately rely on the docs to get the right information.

**Comment by yacinelazaar** [comment]
To address another issue the docs also state that "Encrypted Read Replicas must be encrypted with the same key as the source DB instance". How is this achieved for cross region Read Replicas since KMS key are region constrained?

**Comment by randyurbano** [comment]
This section in the documentation covers creating a read replica in a different AWS Region:

Creating a Read Replica in a Different AWS Region
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReadRepl.html#USER_ReadRepl.XRgn

It includes this text:

"To create an encrypted read replica in another AWS Region, choose Enable Encryption, and then choose the Master key. For the Master key, choose the AWS Key Management Service (AWS KMS) key identifier of the destination AWS Region."

**Comment by randyurbano** [comment]
The recommendation has been updated to the following:

Amazon RDS supports encryption at rest for all DB engines, using keys you manage in AWS Key Management Service (KMS). On a DB instance running with Amazon RDS encryption, data stored at rest in the underlying storage is encrypted, as are its automated backups, Read Replicas, and snapshots. We recommend enabling your DB instance for encryption of data at rest.
