### ISSUE TITLE
Missing moving-to-vpc status description

### ISSUE THREAD

**Issue by julian-alarcon** [awsdocs/amazon-rds-user-guide#26]
Hi

I was checking the documentation, and making a RDS migration from VPC. It now says
DB instance status: **moving-to-vpc**

There is no status information on this section of DB instance status: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.DBInstance.Status.html

There is a good description of the process here: https://aws.amazon.com/premiumsupport/knowledge-center/change-vpc-rds-db-instance/

Also, I think that there is a restriction of the number of movements in parallel but I got no information about this.

**Comment by randyurbano** [comment]
Thanks for your feedback. I will add the moving-to-vpc status to the documentation.

**Comment by randyurbano** [comment]
I added the status.
