### ISSUE TITLE
USER_RebootInstance - grammar issue

### ISSUE THREAD

**Issue by NJohnson9402** [awsdocs/amazon-rds-user-guide#28]
Original text, last part of last paragraph in /awsdocs/amazon-rds-user-guide/tree/master/doc_source/USER_RebootInstance.md

> To improve the reboot time, we recommend that you reduce database activities as much as possible during the reboot process Reduce database activity reduces rollback activity for in-transit transactions.

Should be changed to 2 distinct sentences:

> To improve the reboot time, we recommend that you reduce database activities as much as possible during the reboot process.  Reducing database activity reduces rollback activity for in-transit transactions.

**Comment by randyurbano** [comment]
Thanks for your feedback. I will update the documentation based on your suggestion.

**Comment by randyurbano** [comment]
I updated the documentation:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_RebootInstance.html
