### ISSUE TITLE
Different ways to read SQL Server error log

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [awsdocs/amazon-rds-user-guide#3]
In this page https://github.com/awsdocs/amazon-rds-user-
guide/blob/master/doc_source/Appendix.SQLServer.CommonDBATasks.Logs.md, it says we can use the following command to read the error log:

`EXEC rdsadmin.dbo.rds_read_error_log @index = 0, @type = 1;`

I tried the native command `EXEC sp_readerrorlog` and it also works. So what's the difference and why we need to use `rdsadmin.dbo.rds_read_error_log`?

**Comment by claytran** [comment]
You don't need to use it. It just provides more flexibility because it allows you to specify which log and log type.
