### ISSUE TITLE
Export RDS bin logs

### ISSUE THREAD

**Issue by NisariAIT** [awsdocs/amazon-rds-user-guide#35]
I have enabled read replication(in 2 different AZs) for my RDS instance running mysql v5.7.19. I am trying to get the details about the events that are taking place in the instance. For this, I want the bin logs from the instance. 
I have tried to export the logs using the mysqlbinlog utility in my EC2 and I get the following error:
Command:
```
mysqlbinlog \
    --read-from-remote-server \
    --host=host.rds.amazonaws.com \
    --port=3306  \
    --user username \
    --password password \
    --raw \
    --result-file=/tmp/ \
    mysql-bin-changelog.000105
```

ERROR: Got error reading packet from server: Could not find first log file name in binary log index file.

Could someone please tell me how to export the RDS bin logs to EC2 or to S3 and view the bin logs?

**Comment by randyurbano** [comment]
Thanks for the feedback about the Amazon RDS documentation. Did you review the documentation for RDS MySQL log files?

MySQL Database Log Files
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.MySQL.html

For example, you can publish the log files to Cloudwatch, or you can download them to your local computer:

Publishing MySQL Logs to CloudWatch Logs 
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.MySQL.html#USER_LogAccess.MySQLDB.PublishtoCloudWatchLogs

Accessing MySQL Binary Logs
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.MySQL.html#USER_LogAccess.MySQL.Binarylog

Let me know if this helps.
