### ISSUE TITLE
Using RDS ARN for IAM db auth?

### ISSUE THREAD

**Issue by lra** [awsdocs/amazon-rds-user-guide#36]
Hi,

In https://github.com/awsdocs/amazon-rds-user-guide/blob/master/doc_source/UsingWithRDS.IAMDBAuth.IAMPolicy.md you suggest to use a different ARN format to specify the resource an IAM user can connect to:
```
arn:aws:rds-db:region:account-id:dbuser:dbi-resource-id/database-user-name
```
vs the usual RDS form:
```
arn:aws:rds:us-east-2:123456789012:db:my-mysql-instance-1/database-user-name
```

Notce `rds` vs `rds-db` and `dbuser` vs `db`.

It seems like using the later RDS format works too, but it's not explicit in the doc.

Are both supposed to work? Or is it just an edge case that was forgotten and is not supposed to work?

Once I know, I can PR the doc to make it more explicit if you want.

Thanks!

**Comment by randyurbano** [comment]
Thanks for your feedback on the Amazon RDS documentation. The policy described in the this topic allows an IAM user or role to connect to a DB instance:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.IAMPolicy.html

This ARN format is for use with the rds-db:connect action. As  you said, it is different from the usual RDS ARN format.

Do you mean that created a policy with the rds-db:connect action with the usual RDS ARN format and that the policy enabled connections to a DB instance?

**Comment by lra** [comment]
> Do you mean that created a policy with the rds-db:connect action with the usual RDS ARN format and that the policy enabled connections to a DB instance?

Yes. So I'm wondering if it's intended or it's just some side-effect that we should not rely on.

**Comment by randyurbano** [comment]
I thought the documented ARN was correct for the rds-db:connect action. I will investigate the issue. Thanks again.

**Comment by randyurbano** [comment]
I checked with development. They said you must have other policies on the account that are enabling you to connect. When those policies are removed, IamDbAuth only works with if the remaining policy has “rds-db” and “dbuser” specified.

**Comment by lra** [comment]
Thanks for the clarification, we'll double check on our side and reopen if we manage to replicate on a clean account.

**Comment by atz** [comment]
We would much appreciate a better statement of what the thing being identified by this one-off ARN type is.  What CLI command can I run to list the special `rds-db` ARN, for example?  Does it in fact NOT correspond to any actual resource?

The linked docs (dated 2014) says:

> Don't confuse the `rds-db:` prefix with other RDS API operation prefixes that begin with `rds:`. 
> You use the `rds-db:` prefix and the `rds-db:connect` action only for IAM database authentication. They aren't valid in any other context.
> 
> Currently, the IAM console displays an error for policies with the rds-db:connect action. You can ignore this error.
> 

The IAM console **also** displays an error trying to construct an `arn:aws:rds-db` Resource.  

Almost 5 years later, are we getting *farther* from seeing this capability fully integrated into the console?

This affects are usage of Infrastructure As Code tools, where in every other case we draw an ARN directly from an actual instantiated thing.
