### ISSUE TITLE
pgBadger command does not work for version 10.x

### ISSUE THREAD

**Issue by hectcastro** [awsdocs/amazon-rds-user-guide#37]
In the Common DBA Tasks for PostgreSQL appendix, the pgBadger snippet no longer works for pgBadger version 10.x when used against Amazon RDS for PostgreSQL logs that worked previously:

```bash
$ pgbadger --version
pgBadger version 10.1
$ pgbadger -p '%t:%r:%u@%d:[%p]:' postgresql.log.2018-10-05-15
FATAL: unable to detect log file format from postgresql.log.2018-10-05-15, please use -f option.
```

According to https://github.com/darold/pgbadger/issues/443, this is because pgBadger can no longer automatically detect the log format. The following snippet appears to work consistently:

```
$ pgbadger --version
pgBadger version 10.1
$ pgbadger -f stderr -p '%t:%r:%u@%d:[%p]:' postgresql.log.2018-10-05-15
[========================>] Parsed 56638 bytes of 56638 (100.00%), queries: 11, events: 0
LOG: Ok, generating html report...
```

**Comment by randyurbano** [comment]
There is a pull request for this issue:
https://github.com/awsdocs/amazon-rds-user-guide/pull/38
