### ISSUE TITLE
no UsingWithRDS.IAMDBAuth.Connecting.AWSCLI.PostgreSQL

### ISSUE THREAD

**Issue by gdamjan** [awsdocs/amazon-rds-user-guide#39]
The web page is available at 
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.AWSCLI.PostgreSQL.html 

It also has a small error:

```
export PGPASSWORD="$(aws rds generated-db-auth-token --hostname $RDSHOST --port 3306 --region us-west-2 --username jane_doe )"
```

it should be `aws rds generate-db-auth-token …`

**Comment by randyurbano** [comment]
Thanks for the documentation correction. I updated the topic. I'm sorry about the delay in responding.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.AWSCLI.PostgreSQL.html#UsingWithRDS.IAMDBAuth.Connecting.AWSCLI.AuthToken.PostgreSQL
