### ISSUE TITLE
Import/Export Sql Server Compression Documentation

### ISSUE THREAD

**Issue by sethbacon** [awsdocs/amazon-rds-user-guide#40]
Under Compressing Backup files the docs state:
exec rdsadmin..rds_set_configuration 'S3 **backup c**ompression', 'true'; 
and exec rdsadmin..rds_set_configuration 'S3 backup compression', 'false'; 

These commands fail with Msg 50000, Level 15, State 1, Procedure rds_set_configuration, Line 34
Unrecognized configuration name provided: S3 backup compression 

Correct commands appear to be:
exec rdsadmin..rds_set_configuration 'S3 **Backup C**ompression', 'true';  and 
exec rdsadmin..rds_set_configuration 'S3 Backup Compression', 'false'; 

Note case sensitivity.

**Comment by sethbacon** [comment]
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/SQLServer.Procedural.Importing.html

Sorry, forgot to include the page.

**Comment by sethbacon** [comment]
Anyone...

**Comment by amazoncathan** [comment]
I'll check into this

**Comment by amazoncathan** [comment]
We didn't find this to be case sensitive in our tests. Please try again, and let me know what you ran, and what the error message was.

**Comment by claytran** [comment]
In my tests, it's not case sensitive. Closing the issue.
