### ISSUE TITLE
Missing configuring-iam-database-auth status description 

### ISSUE THREAD

**Issue by MetricMike** [awsdocs/amazon-rds-user-guide#44]
`configuring-iam-database-auth` is missing from the [description table](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.DBInstance.Status.html) and the effects of **Apply Immediately** are also missing from the [PostgreSQL notes](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ModifyPostgreSQLInstance.html#USER_ModifyInstance.Postgres.Settings), (though they do appear in the [MySQL notes](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ModifyInstance.MySQL.html#USER_ModifyInstance.MySQL.Settings)).

**Comment by randyurbano** [comment]
Thanks for your feedback. I will add the missing documentation.

**Comment by randyurbano** [comment]
I updated the documentation. Thanks again.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.DBInstance.Status.html
