### ISSUE TITLE
Colon missing from allowed characters in tag keys/values 

### ISSUE THREAD

**Issue by checkmypi** [awsdocs/amazon-rds-user-guide#51]
Quote from the doc

"The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-' (Java regex: "^([\\p{L}\\p{Z}\\p{N}_.:/=+\\-]*)$")."

But if you look at the regex it seems ':' is also allowed so statement should probably look like
Do note addition of ':'

"The string can contain only the set of Unicode letters, digits, white-space, '_', '.', ':', '/', '=', '+', '-' (Java regex: "^([\\p{L}\\p{Z}\\p{N}_.:/=+\\-]*)$")."

**Comment by randyurbano** [comment]
Thanks for your feedback. I will update the documentation to add ':' (and also '@' was missing).

**Comment by randyurbano** [comment]
I updated the documentation:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Tagging.html#Overview.Tagging

Thanks again for the feedback.
