### ISSUE TITLE
is db.m1.small still supported?

### ISSUE THREAD

**Issue by nazreen** [awsdocs/amazon-rds-user-guide#56]
I believe the smallest instance type supported is now db.t2.micro

**Comment by randyurbano** [comment]
Thanks for the feedback. Could you provide more information about the issue you found in the documentation and a link to the topic with the problem?

**Comment by mjalkio** [comment]
I'm guessing @nazreen is referring to this page: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html

But I don't think the page makes any claim that all instance classes are still supported/available...so I'm not sure if there are actually issues.

**Comment by randyurbano** [comment]
Thanks, closing issue.
