### ISSUE TITLE
Missing prefix for x1 instances on https://aws.amazon.com/rds/instance-types/

### ISSUE THREAD

**Issue by michael-k** [awsdocs/amazon-rds-user-guide#63]
### General

Sadly there's no way to send a pull request for the content on https://aws.amazon.com/rds/instance-types/ and the support is only about billing or technical stuff.  I found no better way than to report it here.

### Missing Prefix

In section `Memory Optimized`, tab `X1`, the models in the tables are missing the `db.` prefix (`x1.16xlarge` vs `db.x1.16xlarge`).

This is relevant, because it makes it harder to scrape the page and use the result to check eg. https://github.com/cloudtools/troposphere/blob/dbf1ab10b02e0efc3c55548c9dee3782af801c9e/troposphere/constants.py#L332-L410 for completeness.

**Comment by randyurbano** [comment]
Thanks for the feedback. I will notify the owners of that web page so that they can correct the problem.

**Comment by randyurbano** [comment]
The owners confirmed that the problem is being corrected. You will probably be able to see the updates sometime next week. Thanks again for your feedback.
