### ISSUE TITLE
Postgres 9.6.12 only allows to go to 10.7.

### ISSUE THREAD

**Issue by bazimov** [awsdocs/amazon-rds-user-guide#64]
Document says 9.6.12 can go to any 10.x version but only allows 10.7.

**Comment by randyurbano** [comment]
Thanks for your feedback. I think the documentation has been updated to specify the correct upgrade targets for version 9.6.12:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion
