### ISSUE TITLE
Wrong version of Postgres for Cloudwatch log publishing

### ISSUE THREAD

**Issue by bigjazzsound** [awsdocs/amazon-rds-user-guide#73]
I am trying to export the cloudwatch logs from my aurora postgres instance running version 9.6.8, but I am getting the following when running the command:

```
$ aws rds modify-db-cluster --db-cluster-identifier <db-cluster-id> --cloudwatch-logs-export-configuration '{"EnableLogTypes":["postgresql", "upgrade"]}'

An error occurred (InvalidParameterCombination) when calling the ModifyDBCluster operation: Engine aurora-postgresql 9.6.8 does not support exporting to CloudWatch Logs. For supported engine versions, see the documentation.
```

The documentation states in <https://github.com/awsdocs/amazon-rds-user-guide/blob/master/doc_source/USER_LogAccess.Concepts.PostgreSQL.md> that "Publishing log files to CloudWatch Logs is only supported for PostgreSQL versions 9.6.6 and above and 10.4 and above."

**Comment by John-Shirley** [comment]
Aurora with PostgreSQL Compatibility does not at this time support exporting logs to CloudWatch logs.

Also note that there are two user guides: one for Amazon RDS and another for Amazon Aurora.

- amazon-rds-user-guide,  https://github.com/awsdocs/amazon-rds-user-guide

- amazon-aurora-user-guide, https://github.com/awsdocs/amazon-aurora-user-guide

When working with an Aurora DB cluster, refer to the Amazon Aurora User Guide.
The Aurora documentation about monitoring an Aurora DB cluster is here:
https://github.com/awsdocs/amazon-aurora-user-guide/blob/master/doc_source/MonitoringOverview.md 
Note this indicates only that you can “export logs for Aurora MySQL”.

Please let me know if you have any other questions or comments.

**Comment by bigjazzsound** [comment]
Ah, my mistake. Thanks for the clarification John.

**Comment by John-Shirley** [comment]
@bigjazzsound , I thought you might like to know that you can now 
publish Aurora PostgreSQL logs to Amazon CloudWatch Logs.
See this: https://github.com/awsdocs/amazon-aurora-user-guide/blob/master/doc_source/AuroraPostgreSQL.CloudWatch.md

**Comment by bigjazzsound** [comment]
@John-Shirley thank you. I have enabled cloudwatch log exports on my clusters running version 10.*, but I am getting the following message on my clusters running Aurora PostgreSQL 9.6.*:

```
An error occurred (InvalidParameterCombination) when calling the ModifyDBCluster operation: Engine aurora-postgresql 9.6.8 does not support exporting to CloudWatch Logs. For
supported engine versions, see the documentation.
```

But I don't see the supported versions of Aurora PostgreSQL in the docs.

**Comment by wormym1011** [comment]
> @bigjazzsound , I thought you might like to know that you can now
> publish Aurora PostgreSQL logs to Amazon CloudWatch Logs.
> See this: https://github.com/awsdocs/amazon-aurora-user-guide/blob/master/doc_source/AuroraPostgreSQL.CloudWatch.md

404 page not found now!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
