### ISSUE TITLE
aws_rds_cluster.enabled_cloudwatch_logs_exports  for aurora postgresql version 10.7 and 9.6.12 does not seems to support upgrade, audit, slowquery and general log types 

### ISSUE THREAD

**Issue by obebode** [awsdocs/amazon-rds-user-guide#80]
I have been trying to use cli to export my aurora-postgresql  logs to cloudwatch but the log types doesn't seems to be supported. 

Here is the error

$ aws rds modify-db-cluster  --db-cluster-identifier xxxxxxx --cloudwatch-logs-export-configuration '{"EnableLogTypes":["postgresql"," upgrade", "audit", "slowquery"]}'

An error occurred (InvalidParameterCombination) when calling the ModifyDBCluster operation: You cannot use the log types ' upgrade', 'audit', 'slowquery' with engine version aurora-postgresql 9.6.12. For supported log types, see the documentation.

I've also tried with aurora-postgres version 10.7 and got the same error. 
Please let me know what log types are supported by this feature for the two versions of aurora as I cannot find it in any of the AWS documentation.  

I have also done extensive reading of this documentation:

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.CloudWatch.html

The cluster-level DB parameter server_audit_logs_upload parameter mentioned in the documentation above doesn't seems to be a valid parameter as I could not find it in my cluster parameter group. Is there something i'm missing or you need to update to your documentation to reflect how it actually works?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
