### ISSUE TITLE
Maintenance window not mentioned for new regions

### ISSUE THREAD

**Issue by wolruf** [awsdocs/amazon-rds-user-guide#81]
On URI:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Maintenance.html
the maintenance time blocks isn't listed for EU (Paris) region as well as Stockholm, Bahrein.

**Comment by randyurbano** [comment]
Thanks for your feedback. I am trying to get the correct information for the Paris AWS Region and for other missing AWS Regions in that table. I'll update the documentation when I have the information.

**Comment by randyurbano** [comment]
I updated the documentation:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Maintenance.html#Concepts.DBMaintenance

**Comment by wolruf** [comment]
Thanks, though the maintenance window is surprinsgly different from Redshift and other regions: https://docs.aws.amazon.com/en_pv/redshift/latest/mgmt/working-with-clusters.html#rs-cluster-maintenance. Any idea or reason why ?

**Comment by randyurbano** [comment]
Sorry, but I'm not sure why Redshift is different. I informed the development team, and they will look into it. Thanks again for your feedback.
