### ISSUE TITLE
Combined CA Bundle needs to be updated

### ISSUE THREAD

**Issue by bsharin** [awsdocs/amazon-rds-user-guide#88]
Line 22 of the user guide has reference to combined ca bundle available to download,  https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem, but it has not been updated with the latest certificate.  

$ openssl x509 -enddate -noout -in rds-combined-ca-bundle.pem
`notAfter=Mar  5 09:11:31 2020 GMT`

**Comment by randyurbano** [comment]
The certificate bundle contains certificates for both the old and new CA, so you can upgrade your application safely and maintain connectivity during the transition period. 

You can use the Java keytool utility to print all the certificates in the combined .pem file and validate the expiry date for each. For example, you can run the following command:

keytool -printcert -file rds-combined-ca-bundle.pem | egrep “Owner:|Issuer|Valid”

**Comment by bsharin** [comment]
Ah! thank you for the clarification.
