### ISSUE TITLE
Unknown options: --headers

### ISSUE THREAD

**Issue by anupsom** [awsdocs/amazon-rds-user-guide#92]
On OSX
aws rds describe-db-instances --db-instance-identifier AcmeRDS --headers

returns
**Unknown options: --headers**

**Comment by max-webster** [comment]
I ran a quick check to see if --headers was valid in some specific context, such as in combination with '--output text'. It doesn't appear to be valid in any circumstances. The example as it is would return output in JSON format, so the header info would be shown in the form of JSON keys. If '--output text' was added to the example, then the header info would be shown in a tabular format, but AFAIK there's no way to suppress the header line, there's no special option to display it or not.

**Comment by randyurbano** [comment]
I updated the example:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MySQL.Procedural.Importing.AnySource.html#MySQL.Procedural.Importing.AnySource.Step4
