### ISSUE TITLE
What do pg_transport errors mean

### ISSUE THREAD

**Issue by adefemi-adeyemi** [awsdocs/amazon-rds-user-guide#97]
I'm running pg_transport and receiving odd errors:

``` no extensions except for pg_transport can be installed to use pg_transport```

This error makes no sense and if we are required to have pg_statements and pg_transport as part of our standard_libraries in Postgres 11.5

**Comment by steveh** [comment]
I'm not sure if I'm understanding it properly either - just about every database we use has at least `btree_gist` and `pgcrypto`/`uuid-ossp` installed, so it's not useful if we have to delete all those columns

**Comment by randyurbano** [comment]
I closed the issue because it was filed a long time ago, and I didn't see a specific problem with the documentation mentioned in the comments. If there is an issue in the documentation, I can re-open the issue.
