### ISSUE TITLE
typo in CHAP_Storage.md

### ISSUE THREAD

**Issue by vivisquirrel** [awsdocs/amazon-rds-user-guide#98]
https://github.com/awsdocs/amazon-rds-user-guide/blob/master/doc_source/CHAP_Storage.md#combining-provisioned-iops-storage-with-multi-az-deployments-or-read-replicas

> You can also use Provisioned IOPS SSD storage with read replicas for MySQL, MariaDB or PostgreSQL. The type of storage for a read replica is independent of that on the master DB instance. **For example, you might use General Purpose SSD for read replicas ith a master DB instance that uses Provisioned IOPS SSD storage to reduce costs.** However, your read replica's performance in this case might differ from that of a configuration where both the master DB instance and the read replicas use Provisioned IOPS SSD storage.

For example, you might use General Purpose SSD for read replicas **_ith_** a master DB instance that uses Provisioned IOPS SSD storage to reduce costs. 

'ith' should be 'with'. it's a little typo.

**Comment by claytran** [comment]
thanks! will be fixed in the doc next time it's published
