### ISSUE TITLE
DownloadCompleteDBLogFile API action - deprecated?

### ISSUE THREAD

**Issue by swoldemi** [awsdocs/amazon-rds-user-guide#99]
https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonrds.html references the `DownloadCompleteDBLogFile` API action which links to here https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/RESTReference.html#RESTReference.DownloadCompleteDBLogFile

This link is broken and redirects to the home page of the RDS User Guide: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Welcome.html

This API does not exist int he API documentation (control, data, and insights) so I suspect it's been deprecated and should be removed from the table. Is this correct?
Control API actions: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_Operations.html

**Comment by randyurbano** [comment]
Thanks for your feedback. The documentation has been corrected:

https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonrds.html
